In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

# import train_test_split

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3) 

# logistic regression on datasets
ovr means one over others

In [3]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9685185185185186

# Search Vector Machine

In [6]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.5333333333333333

# Random Forset

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9814814814814815

# cross val score function

In [13]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(solver="liblinear",multi_class ='ovr'), digits.data,digits.target,cv=3)

array([0.89534884, 0.94991653, 0.90939597])

In [18]:
cross_val_score(SVC(gamma="auto"),digits.data,digits.target, cv=3)

array([0.39368771, 0.41068447, 0.45973154])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=3)

array([0.92524917, 0.94156928, 0.92785235])

# import iris dataset 
and applied cross val score function

In [32]:
import pandas as pd

In [27]:
from sklearn.datasets import load_iris

In [28]:
iris = load_iris()

In [29]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [30]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [33]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [37]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [45]:
df.target.unique()

array([0, 1, 2])

In [43]:
df["target"]= iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [48]:
df["flower_names"] = df.target.apply(lambda x:iris.target_names[x])
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target target_names flower_names  
0       0       setosa       setosa  
1       0       setosa       setosa  
2       0       setosa       setosa  
3       0       setosa       setosa  
4       0       setosa       setosa  
5       0       setosa       setosa  
6       0       setosa       setosa  
7       0       setosa       setosa  
8       0       setosa       setosa  
9       0       setosa       setosa

In [54]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data,iris.target,cv=3)

array([0.96078431, 0.92156863, 0.95833333])

In [55]:
cross_val_score(SVC(gamma="auto"), iris.data,iris.target,cv=3)

array([0.98039216, 0.96078431, 0.97916667])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data,iris.target, cv=3)

array([0.98039216, 0.94117647, 0.95833333])

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [61]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)

array([0.98039216, 0.92156863, 0.97916667])

# SVM is the best fit model